apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: qiosss
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qiosss
    app.kubernetes.io/part-of: qiosss
  name: qiosss
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: qiosss
status:
  loadBalancer: {}
